### ISSUE TITLE
User can navigate through each page within the webapp

### ISSUE THREAD

**Issue by OMHavec** [SCCapstone/CapstoneProject#16]

**Comment by josemvidal** [comment]
I can confirm, this has not been implemented, except for the Calendar:


https://user-images.githubusercontent.com/228704/144745651-079fc008-0b82-4c2c-ae6e-e8d2515846dd.mp4

**Comment by DaRosc** [comment]
@josemvidal @OMHavec @Nicolas-A-Becker @ctreid @laurenelee99 Looking at your calendar page, it doesn't appear to be the latest version of main from my end. Also, when we are running this locally, any page that requires the database needs a multitude of external software to work and a specifically designed database inside MySQL so that could be the reason those pages aren't viewable for you. That should not be a problem when the database has been hosted externally.


https://user-images.githubusercontent.com/70486885/144751569-f8c3c275-9a10-4fbb-ab5d-47743657cbfe.mp4


https://user-images.githubusercontent.com/70486885/144751582-7502850c-6368-4260-ae1f-f10dd3b23345.mp4
