### ISSUE TITLE
Shopping page will persistently display shopping items

### ISSUE THREAD

**Issue by ghost** [SCCapstone/CapstoneProject#17]

**Comment by josemvidal** [comment]
I can confirm, this has not been implemented.


Uploading 2021-12-05_06-59-11.mp4…

**Comment by DaRosc** [comment]
@josemvidal @OMHavec @Nicolas-A-Becker @ctreid @laurenelee99 When the development server is run locally, any page that requires the database needs a multitude of external software to work and a specifically designed database inside MySQL so that could be the reason those pages aren't viewable for you. That should not be a problem when the database has been hosted externally.

https://user-images.githubusercontent.com/70486885/144751980-c37473b9-d774-49b8-9ab3-254e574a264c.mp4


https://user-images.githubusercontent.com/70486885/144752149-c2383f68-cb6d-4148-931d-5b0e4347ac1f.mp4

**Comment by josemvidal** [comment]
Got it. Note that we test the deployed version.
