### ISSUE TITLE
Calendar page will persistently display calendar entries

### ISSUE THREAD

**Issue by OMHavec** [SCCapstone/CapstoneProject#19]

**Comment by josemvidal** [comment]
I guess this is open because you do not just want to just embed a google calendar in your page. You want to actually show events brought in from your database.

I agree, embedding a google calendar is something only a static website should do.

**Comment by ctreid** [comment]
While our original plan was to custom make a calendar that would add events to a database for each user, we have since decided to use an embedded google calendar. We identified that it could be a potential security risk to be storing events without moderation. Additionally, users would be less likely to use a custom-built calendar page when there is a better option of syncing the information together. This provides users of our website the ease of cross-platform compatibility with their calendar, as you can sync your outlook calendar with your google calendar, and then both will show up on this page without any additional user entry. 

We have decided to use the Reminders portion of the page to allow users to enter time-sensitive goals or events, which will be pulled from the database.

**Comment by ctreid** [comment]
Closed in merge and pull #53. I was waiting to officially close this issue to see if there was a reply, but this has been completed.
