### ISSUE TITLE
User inputs for contact information, shopping items, and calendar entries will be saved to and retrieved from a SQL database

### ISSUE THREAD

**Issue by OMHavec** [SCCapstone/CapstoneProject#20]

**Comment by josemvidal** [comment]
Not implemented, I guess....

**Comment by DaRosc** [comment]
@josemvidal @OMHavec @Nicolas-A-Becker @ctreid @laurenelee99 Looking at your calendar page, it doesn't appear to be the latest version of main from my end. Also, when we are running this locally, any page that requires the database needs a multitude of external software to work and a specifically designed database inside MySQL so that could be the reason those pages that require the database aren't viewable for you. That should not be a problem when the database has been hosted externally.

https://user-images.githubusercontent.com/70486885/144752359-ac3a434f-64c2-489b-b03f-a2d32136160e.mp4


https://user-images.githubusercontent.com/70486885/144752369-4151444a-cda3-4eec-9c50-0f6e3bb9c55d.mp4

**Comment by josemvidal** [comment]
Got it. Note that we test the deployed version.

**Comment by Nicolas-A-Becker** [comment]
https://github.com/SCCapstone/CapstoneProject/commit/202db8098d3500e955c46226d969beadceb7a339

**Comment by josemvidal** [comment]
**Tip:** If you just write "closes #X" in the comment of the git-commit, where X is the issue number you want to close. See [linking pull requests to issues using keywords](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more information, or [watch this video](https://youtu.be/WMykv2ZMyEQ).

You should also write "#X" on any commit that is for #X. That commit will then get automatically linked to the Issue.

See my [github tips list](https://capstone.cse.sc.edu/lecture/github-issues/#tips) for all the tips.
