### ISSUE TITLE
Add Beta Issues

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CapstoneProject#57]
Add the features you will implement for the [Beta Milestone](https://capstone.cse.sc.edu/milestone/beta/) and associate them with that Milestone.

Close this when you are done adding them. I will then look at them and tell you if I approve them or not.

This should be done in the first couple of weeks of classes.

**Comment by OMHavec** [comment]
Beta Release Milestone Issues have been created.
#65 #66 #67 #69 #70

**Comment by josemvidal** [comment]
So, I don't remember what already works.

For the Beta we want the core functionality implemented, this means users can CRUD personal information, grocery lists, calendars, and also chat. Will these things be working for the Beta? I don't see any Issues about users entering or editing data.

**Comment by josemvidal** [comment]
Please answer the above 🙏

**Comment by josemvidal** [comment]
I am still waiting for you to answer the above 🔥

**Comment by OMHavec** [comment]
Users will be able to CRUD personal info (+ all other information on settings pages), shopping list entries, and calendar entries. The chat page is being scrapped in favor of a chores list, which will also be ready for users to CRUD.

**Comment by josemvidal** [comment]
Too late. I did not approve your Beta Issues.

@ICanNomNoms We will have to determine what the core functionality is and grade based on that. We can use https://github.com/SCCapstone/CapstoneProject/milestone/6 as a guideline.

**Comment by ctreid** [comment]
@josemvidal @ICanNomNoms Sorry for any confusion that we may have caused. Our core functionality is what was linked with our Beta Issues. This includes: 

1. Google sign in (#65)
2. Pages that are uniquely populated for each user based on their room number (#66)
3. Shopping Page and Chore Page that will display the same list of items for all the roommates. Each roommate will be able to add or remove items from the list. (#67)
4. The users Google Calendar will be linked to the page. When roommates share their calendars with each other, they will also be able to see each other's calendars. The link for their calendar will be added manually in their individual settings page. (#69)
5. When a roommate creates a new room, they will be given a pin that the other roommates will use to join that room. Once the pin is entered after sign-in, the roommates will be able to see their room-specific Home, Calendar, Shopping, Chores, and Settings. (#70)

Our issues did not explicitly state what each page's user interaction would and would not include because every page would require its own version of interaction, such as entering items into a list or providing their google sign-in. We did not go into great detail in the explanation, but we have learned from this and in the future, we will make sure everything is written even more explicitly so we do not run into this issue. 

All of these issues are completed and closed. Due to a recent update to composer, we were struggling with deployment. At the moment, our site is deployed, but the CSS is not working correctly. We are working to make sure this is fixed ASAP as previously, this was not an issue before our server crashed.  All of our issues for Beta Release have been completed and closed. I will mention, we are struggling with Google sign-in in Google Chrome, but it is working in other browsers such as Safari and Opera. I apologize for the inconvenience that this may cause, but we are working through these bugs one at a time.
